services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/toDo-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=toDo-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}